### NumPy Assignment: Banking Industry Analysis

In [2]:
import numpy as np

# Create banking data: 10 rows × 5 columns
# Columns: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active

banking_data = np.array([
    [2001, 12500, 720, 35, 5],
    [2002, 8400, 680, 22, 3],
    [2003, 15600, 750, 40, 7],
    [2004, 4300, 610, 18, 2],
    [2005, 9800, 700, 27, 4],
    [2006, 21000, 810, 55, 10],
    [2007, 6700, 640, 20, 3],
    [2008, 14300, 730, 38, 6],
    [2009, 5200, 660, 25, 4],
    [2010, 18700, 790, 48, 9]
])

banking_data

array([[ 2001, 12500,   720,    35,     5],
       [ 2002,  8400,   680,    22,     3],
       [ 2003, 15600,   750,    40,     7],
       [ 2004,  4300,   610,    18,     2],
       [ 2005,  9800,   700,    27,     4],
       [ 2006, 21000,   810,    55,    10],
       [ 2007,  6700,   640,    20,     3],
       [ 2008, 14300,   730,    38,     6],
       [ 2009,  5200,   660,    25,     4],
       [ 2010, 18700,   790,    48,     9]])

### Question 1: Array Creation and Manipulation

In [3]:
# **Q1.1:** Create a 4x4 identity matrix using `np.eye()`

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# **Q1.2:** Create an array of 8 zeros using `np.zeros()`

zeros_array = np.zeros(8)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# **Q1.3:** Create an array of 6 ones using `np.ones()`

ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [6]:

# **Q1.4:** Create an array with values from 0 to 15 using `np.arange()`

range_array = np.arange(16)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [7]:
# **Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`

linspace_array = np.linspace(0, 100, 8)
print(linspace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


### Question 2: Array Attributes and Information

In [8]:
# **Q2.1:** What is the shape of the `banking_data` array?

print(banking_data.shape)

(10, 5)


In [9]:
# **Q2.2:** What is the data type of the `banking_data` array?

print(banking_data.dtype)

int64


In [10]:
# **Q2.3:** What is the size (total number of elements) of the `banking_data` array?

print(banking_data.size)

50


In [11]:
# **Q2.4:** What is the number of dimensions of the `banking_data` array?

print(banking_data.ndim)

2


In [12]:
# **Q2.5:** What is the memory size of the `banking_data` array in bytes?

print(f'{banking_data.nbytes} bytes')

400 bytes


### Question 3: Indexing and Slicing

In [13]:
# **Q3.1:** Extract the first row of `banking_data`

print(banking_data[0])

[ 2001 12500   720    35     5]


In [14]:
# **Q3.2:** Extract the last row of `banking_data`

print(banking_data[-1])

[ 2010 18700   790    48     9]


In [15]:
# **Q3.3:** Extract the Account_Balance column (column index 1)

print(banking_data[:,1])

[12500  8400 15600  4300  9800 21000  6700 14300  5200 18700]


In [16]:
# **Q3.4:** Extract the first 4 rows and first 3 columns

print(banking_data[:4,:3])

[[ 2001 12500   720]
 [ 2002  8400   680]
 [ 2003 15600   750]
 [ 2004  4300   610]]


In [17]:
# **Q3.5:** Extract rows 3 to 7 (inclusive)

print(banking_data[3:8])

[[ 2004  4300   610    18     2]
 [ 2005  9800   700    27     4]
 [ 2006 21000   810    55    10]
 [ 2007  6700   640    20     3]
 [ 2008 14300   730    38     6]]


### Question 4: Mathematical Operations

In [18]:
# **Q4.1:** Calculate the sum of all account balances

print(f'All total account balances: {sum(banking_data[:,1])}')

All total account balances: 116500


In [19]:
# **Q4.2:** Calculate the mean account balance

print(f'Mean: {np.mean(banking_data[:, 1])}')

Mean: 11650.0


In [20]:
# **Q4.3:** Calculate the standard deviation of account balances

print(f'Standard deviation: {np.std(banking_data[:,1]):.2f}')

Standard deviation: 5427.57


In [21]:
# **Q4.4:** Calculate the variance of account balances

print(f'Variance: {np.var(banking_data[:,1]):.2f}')

Variance: 29458500.00


In [22]:
# **Q4.5:** Calculate the median account balance

print(f'Median: {np.median(banking_data[:,1]):.2f}')

Median: 11150.00


### Question 5: Statistical Functions

In [23]:
# **Q5.1:** Find the minimum and maximum account balances

print(f'Minimum acount balence: {np.min(banking_data[:,1]):.2f}')
print(f'Maximum acount balence: {np.max(banking_data[:,1]):.2f}')

Minimum acount balence: 4300.00
Maximum acount balence: 21000.00


In [24]:
# **Q5.2:** Find the minimum and maximum credit scores

print(f'Minimum Credit Scores: {np.min(banking_data[:,2]):.2f}')
print(f'Maximum Credit Scores: {np.max(banking_data[:,2]):.2f}')

Minimum Credit Scores: 610.00
Maximum Credit Scores: 810.00


In [25]:
# **Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)

percentile_ = np.percentile(banking_data[:,1], [25, 50, 75])
print(f'25th Parcentile Acount Balence: {percentile_[0]}')
print(f'50th Parcentile Acount Balence: {percentile_[1]}')
print(f'75th Parcentile Acount Balence: {percentile_[2]}')

25th Parcentile Acount Balence: 7125.0
50th Parcentile Acount Balence: 11150.0
75th Parcentile Acount Balence: 15275.0


In [26]:
# **Q5.4:** Calculate the correlation between account balance and credit score

correlation = np.corrcoef(banking_data[:,1], banking_data[:,2])[0,1]
print(f'correlation: {correlation:.4f}')

correlation: 0.9824


In [27]:
# **Q5.5:** Calculate the covariance between account balance and credit score

print(f'Covarience b/w acount balence and credit score: {np.cov(banking_data[:,1], banking_data[:,2])[0,1]:.4f} ')

Covarience b/w acount balence and credit score: 359833.3333 


### Question 6: Array Reshaping and Manipulation

In [28]:
# **Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns

print(f'Reshaping the data:\n {banking_data.reshape(5, 10)}')

Reshaping the data:
 [[ 2001 12500   720    35     5  2002  8400   680    22     3]
 [ 2003 15600   750    40     7  2004  4300   610    18     2]
 [ 2005  9800   700    27     4  2006 21000   810    55    10]
 [ 2007  6700   640    20     3  2008 14300   730    38     6]
 [ 2009  5200   660    25     4  2010 18700   790    48     9]]


In [29]:
# **Q6.2:** Flatten the `banking_data` to a 1D array

print(f'Flatten data: {banking_data.flatten()}')

Flatten data: [ 2001 12500   720    35     5  2002  8400   680    22     3  2003 15600
   750    40     7  2004  4300   610    18     2  2005  9800   700    27
     4  2006 21000   810    55    10  2007  6700   640    20     3  2008
 14300   730    38     6  2009  5200   660    25     4  2010 18700   790
    48     9]


In [30]:
# **Q6.3:** Transpose the `banking_data`

print(f'Transpose the data:\n {banking_data.T}')

Transpose the data:
 [[ 2001  2002  2003  2004  2005  2006  2007  2008  2009  2010]
 [12500  8400 15600  4300  9800 21000  6700 14300  5200 18700]
 [  720   680   750   610   700   810   640   730   660   790]
 [   35    22    40    18    27    55    20    38    25    48]
 [    5     3     7     2     4    10     3     6     4     9]]


In [31]:
# **Q6.4:** Split the `banking_data` into 2 equal parts vertically

print(f' Spliting vertically 2 equal parts:\n part 1:\n{np.vsplit(banking_data, 2)[0]}\n part 2:\n {np.vsplit(banking_data, 2)[1]}')

 Spliting vertically 2 equal parts:
 part 1:
[[ 2001 12500   720    35     5]
 [ 2002  8400   680    22     3]
 [ 2003 15600   750    40     7]
 [ 2004  4300   610    18     2]
 [ 2005  9800   700    27     4]]
 part 2:
 [[ 2006 21000   810    55    10]
 [ 2007  6700   640    20     3]
 [ 2008 14300   730    38     6]
 [ 2009  5200   660    25     4]
 [ 2010 18700   790    48     9]]


In [32]:
# **Q6.5:** Split the `banking_data` into 2 equal parts horizontally

print(f' Spliting horizontally 2 equal parts:\n part 1:\n{np.array_split(banking_data, 2, axis=1)[0]}\n part 2:\n {np.array_split(banking_data, 2, axis=1)[1]}')

 Spliting horizontally 2 equal parts:
 part 1:
[[ 2001 12500   720]
 [ 2002  8400   680]
 [ 2003 15600   750]
 [ 2004  4300   610]
 [ 2005  9800   700]
 [ 2006 21000   810]
 [ 2007  6700   640]
 [ 2008 14300   730]
 [ 2009  5200   660]
 [ 2010 18700   790]]
 part 2:
 [[35  5]
 [22  3]
 [40  7]
 [18  2]
 [27  4]
 [55 10]
 [20  3]
 [38  6]
 [25  4]
 [48  9]]


### Question 7: Logical Operations and Filtering

In [33]:
# **Q7.1:** Find customers with account balance greater than $100,000

print(banking_data[banking_data[:, 1] > 100000]) 
#output is empty because we dont have acount balence greater than 1 lakh

[]


In [34]:
# **Q7.2:** Find customers with credit score greater than 800

print(banking_data[banking_data[:, 2] > 800])

[[ 2006 21000   810    55    10]]


In [35]:
# **Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750

print(banking_data[(banking_data[:, 3] > 50) & (banking_data[:, 2] < 750)])

[]


In [36]:
# **Q7.4:** Count how many customers have account balance between $10,000 and $100,000

print(np.sum((banking_data[:, 1] >= 10000) & (banking_data[:,1] <= 100000)))

5


In [37]:
# **Q7.5:** Find the index of the customer with the highest credit score

print(f'Index: {np.argmax(banking_data[:, 2])} hihest credit score {banking_data[np.argmax(banking_data[:, 2]),2]}')

Index: 5 hihest credit score 810


### Question 8: Sorting and Searching

In [38]:
# **Q8.1:** Sort the `banking_data` by account balance (ascending)

print(banking_data[(banking_data[:,1].argsort())])

[[ 2004  4300   610    18     2]
 [ 2009  5200   660    25     4]
 [ 2007  6700   640    20     3]
 [ 2002  8400   680    22     3]
 [ 2005  9800   700    27     4]
 [ 2001 12500   720    35     5]
 [ 2008 14300   730    38     6]
 [ 2003 15600   750    40     7]
 [ 2010 18700   790    48     9]
 [ 2006 21000   810    55    10]]


In [39]:
# **Q8.2:** Sort the `banking_data` by credit score (descending)

print(banking_data[(banking_data[:,2].argsort()[::-1])])

[[ 2006 21000   810    55    10]
 [ 2010 18700   790    48     9]
 [ 2003 15600   750    40     7]
 [ 2008 14300   730    38     6]
 [ 2001 12500   720    35     5]
 [ 2005  9800   700    27     4]
 [ 2002  8400   680    22     3]
 [ 2009  5200   660    25     4]
 [ 2007  6700   640    20     3]
 [ 2004  4300   610    18     2]]


In [40]:
# **Q8.3:** Find the indices that would sort the array by years active

print(np.argsort(banking_data[:, 4]))

[3 1 6 4 8 0 7 2 9 5]


In [41]:
# **Q8.4:** Find the customer with the second highest account balance
second_heighest_balence = np.argsort(banking_data[:, 1])[-2]
second_heighest_customer = banking_data[second_heighest_balence]
print(f'Customer ID: {second_heighest_customer[0]} Account balence: {second_heighest_customer[1]}')

Customer ID: 2010 Account balence: 18700


In [42]:
# **Q8.5:** Find the customer with the lowest transaction count

lowest_tansaction = np.argmin(banking_data[:, 3])
lowest_customer = banking_data[lowest_tansaction]
print(f'Customer_ID: {lowest_customer[0]} lowest_transaction_count: {lowest_customer[1]}')

Customer_ID: 2004 lowest_transaction_count: 4300


### Question 9: Mathematical Functions

In [43]:
# **Q9.1:** Calculate the absolute values of all elements

print(np.abs(banking_data))

[[ 2001 12500   720    35     5]
 [ 2002  8400   680    22     3]
 [ 2003 15600   750    40     7]
 [ 2004  4300   610    18     2]
 [ 2005  9800   700    27     4]
 [ 2006 21000   810    55    10]
 [ 2007  6700   640    20     3]
 [ 2008 14300   730    38     6]
 [ 2009  5200   660    25     4]
 [ 2010 18700   790    48     9]]


In [44]:
# **Q9.2:** Calculate the square root of all account balances

print(np.sqrt(banking_data[:,1]))

[111.80339887  91.6515139  124.89995997  65.57438524  98.99494937
 144.91376746  81.85352772 119.58260743  72.11102551 136.74794331]


In [45]:
# **Q9.3:** Calculate the square of all credit scores

print(np.square(banking_data[:, 2]))

[518400 462400 562500 372100 490000 656100 409600 532900 435600 624100]


In [46]:
# **Q9.4:** Calculate the exponential of all transaction counts

print(np.exp(banking_data[:,3]))

[1.58601345e+15 3.58491285e+09 2.35385267e+17 6.56599691e+07
 5.32048241e+11 7.69478527e+23 4.85165195e+08 3.18559318e+16
 7.20048993e+10 7.01673591e+20]


In [47]:
# **Q9.5:** Calculate the natural logarithm of all account balances

print(np.log(banking_data[:, 1]))

[9.43348392 9.03598698 9.65502619 8.3663703  9.19013766 9.95227772
 8.80986281 9.56801482 8.5564139  9.8362788 ]


### Question 10: Advanced Operations

In [48]:
# **Q10.1:** Calculate the cumulative sum of account balances

print(np.cumsum(banking_data[:, 1]))

[ 12500  20900  36500  40800  50600  71600  78300  92600  97800 116500]


In [49]:
# **Q10.2:** Calculate the cumulative product of transaction counts

print(np.cumprod(banking_data[:, 3]))

[             35             770           30800          554400
        14968800       823284000     16465680000    625695840000
  15642396000000 750835008000000]


In [50]:
# **Q10.3:** Calculate the difference between consecutive account balances

print(np.diff(banking_data[:, 1]))

[ -4100   7200 -11300   5500  11200 -14300   7600  -9100  13500]


In [51]:
# **Q10.4:** Calculate the gradient of account balances

print(np.gradient(banking_data[:, 1]))

[-4100.  1550. -2050. -2900.  8350. -1550. -3350.  -750.  2200. 13500.]


In [52]:
# **Q10.5:** Calculate the histogram of account balances with 5 bins

Histogram_Counts, Bins_edges = np.histogram(banking_data[:, 1], bins=5)
print(f"Histogram Counts = {Histogram_Counts}, Bins edges = {Bins_edges}")

Histogram Counts = [3 2 2 1 2], Bins edges = [ 4300.  7640. 10980. 14320. 17660. 21000.]


### Question 11: Random Numbers and Simulation

In [53]:
# **Q11.1:** Generate 6 random integers between 1 and 1000

print(np.random.randint(1, 101, 6))

[93 22 82 65 96 48]


In [54]:
# **Q11.2:** Generate 6 random floats between 0 and 1

print(np.random.random(6))

[0.82173513 0.51854164 0.5123     0.11408096 0.00713175 0.58529845]


In [55]:
# **Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)

print(np.random.normal(700, 100, 6))

[667.53356867 729.68583361 741.97609448 751.85043614 561.95685258
 639.16329536]


In [56]:
# **Q11.4:** Shuffle the `banking_data` rows randomly

shuffled = banking_data.copy()
np.random.shuffle(shuffled)
print(shuffled)

[[ 2009  5200   660    25     4]
 [ 2001 12500   720    35     5]
 [ 2006 21000   810    55    10]
 [ 2007  6700   640    20     3]
 [ 2003 15600   750    40     7]
 [ 2005  9800   700    27     4]
 [ 2004  4300   610    18     2]
 [ 2002  8400   680    22     3]
 [ 2008 14300   730    38     6]
 [ 2010 18700   790    48     9]]


In [57]:
# **Q11.5:** Set random seed to 123 and generate 4 random numbers

np.random.seed(123)
seeded_random = np.random.random(4)
print(seeded_random)

[0.69646919 0.28613933 0.22685145 0.55131477]


### Question 12: Linear Algebra Operations

In [58]:
# **Q12.1:** Calculate the dot product of account balance and credit score columns

dot_product = np.dot(banking_data[:, 1], banking_data[:, 2])
print(f"{dot_product:.2f}")

85837000.00


In [59]:
# **Q12.2:** Calculate the cross product of first two rows

print(np.cross(banking_data[0,:3], banking_data[1,:3]))

[ 2452000    80760 -8216600]


In [60]:
# **Q12.3:** Calculate the norm (magnitude) of the account balance column

print(f"{np.linalg.norm(banking_data[:, 1]):.2f}")

40642.47


In [61]:
# **Q12.4:** Create a 3x3 matrix and calculate its determinant

matrix = np.array([
    [3, 5, 6],
    [3, 2, 8],
    [9, 4, 1]
])
print(matrix)
print(np.linalg.det(matrix))

[[3 5 6]
 [3 2 8]
 [9 4 1]]
219.00000000000023


In [62]:
# **Q12.5:** Calculate the inverse of the 3x3 matrix

print(np.linalg.inv(matrix))

[[-0.1369863   0.08675799  0.12785388]
 [ 0.31506849 -0.23287671 -0.02739726]
 [-0.02739726  0.15068493 -0.04109589]]


#### Question 13: String Operations

In [63]:
# **Q13.1:** Convert all customer IDs to strings

to_String = banking_data[:, 0].astype(str)
print(to_String)

['2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009' '2010']


In [64]:
# **Q13.2:** Check if any customer ID contains '200'

print(np.char.find(to_String, '200') >= 0)

[ True  True  True  True  True  True  True  True  True False]


In [65]:
# **Q13.3:** Convert all customer IDs to uppercase (if they were strings)

print(np.char.upper(to_String))

['2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009' '2010']


In [66]:
# **Q13.4:** Count the length of each customer ID string

print(np.char.str_len(to_String))

[4 4 4 4 4 4 4 4 4 4]


In [67]:
# **Q13.5:** Replace '200' with 'CUST' in customer IDs

replace_ = np.char.replace(to_String, '200', 'CUST')
print(replace_)

['CUST1' 'CUST2' 'CUST3' 'CUST4' 'CUST5' 'CUST6' 'CUST7' 'CUST8' 'CUST9'
 '2010']


#### Question 14: Date and Time Operations

In [68]:
# **Q14.1:** Convert years active to months

print(banking_data[:, 4] * 12)

[ 60  36  84  24  48 120  36  72  48 108]


In [69]:
# **Q14.2:** Calculate the average years active

print(f"The average years active: {np.mean(banking_data[:, 4])}")

The average years active: 5.3


In [70]:
# **Q14.3:** Find customers who have been active for more than 5 years

print(banking_data[banking_data[:, 4] > 5])

[[ 2003 15600   750    40     7]
 [ 2006 21000   810    55    10]
 [ 2008 14300   730    38     6]
 [ 2010 18700   790    48     9]]


In [71]:
# **Q14.4:** Calculate the total time all customers have been active (in years)

print(f"The total time all customers active in {np.sum(banking_data[:, 4])} years.")

The total time all customers active in 53 years.


In [72]:
# **Q14.5:** Find the customer with the shortest time active

shortest = np.argmin(banking_data[:, 4])
shortest_time_customer = banking_data[shortest]
print(f"Product_id: {shortest_time_customer[0]}, Shortest_time: {shortest_time_customer[4]}")

Product_id: 2004, Shortest_time: 2


#### Question 15: Advanced Array Operations

In [73]:
# **Q15.1:** Apply a function to calculate 5% interest on all account balances

def interest_balance(x):
    return x+x*0.05

print(interest_balance(banking_data[:, 1]))

[13125.  8820. 16380.  4515. 10290. 22050.  7035. 15015.  5460. 19635.]


In [74]:
# **Q15.2:** Use `np.where` to categorize customers by balance ranges

balence = banking_data[:,1]
categorize = np.where(balence < 5000, "Low Balence", 
                      np.where(balence < 10000, 'Medium Balence', 'High Balence'))
print(categorize)

['High Balence' 'Medium Balence' 'High Balence' 'Low Balence'
 'Medium Balence' 'High Balence' 'Medium Balence' 'High Balence'
 'Medium Balence' 'High Balence']


In [75]:
# **Q15.3:** Use `np.select` to categorize customers by credit score ranges

credit_score = banking_data[:, 2]
condition = [credit_score < 250, (credit_score >= 550) & (credit_score < 700), credit_score >= 700]
choices = ["Credit score is low", "Credit score is medium", "Credit score is high"]
categorize = np.select(condition, choices, default="Unknown")
print(categorize)

['Credit score is high' 'Credit score is medium' 'Credit score is high'
 'Credit score is medium' 'Credit score is high' 'Credit score is high'
 'Credit score is medium' 'Credit score is high' 'Credit score is medium'
 'Credit score is high']


In [76]:
# **Q15.4:** Use `np.piecewise` to apply different interest rates based on balance

def low_intrest(x): return x+x*0.3
def medium_intrest(x): return x+x*0.5
def high_intrest(x): return x+x*0.8
# np.piecewise(array, conditions, functions)
intrest_per_balance = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 6000, (banking_data[:, 1] >= 6000) & (banking_data[:, 1] < 12000), banking_data[:, 1] >= 12000],
    [low_intrest, medium_intrest, high_intrest]
)
print(intrest_per_balance)

[22500 12600 28080  5590 14700 37800 10050 25740  6760 33660]


In [77]:
# **Q15.5:** Use `np.apply_along_axis` to calculate the sum of each row

# np.apply_along_axis(function, axis, array)
sum_of_row = np.apply_along_axis(np.sum, 1, banking_data)
print(sum_of_row)

[15261 11107 18400  6934 12536 23881  9370 17082  7898 21557]


#### Question 16: Array Concatenation and Stacking

In [78]:
# **Q16.1:** Concatenate two arrays horizontally using `np.hstack()`

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 8])
hstacked = np.hstack([arr1, arr2])
print(hstacked)

[1 2 3 4 5 8]


In [79]:
# **Q16.2:** Concatenate two arrays vertically using `np.vstack()`

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 8])
vstaked = np.vstack([arr1, arr2])
print(vstaked)

[[1 2 3]
 [4 5 8]]


In [80]:
# **Q16.3:** Concatenate arrays along a specific axis using `np.concatenate()`

concatenated = np.concatenate([arr1, arr2], axis = 0)
print(concatenated)

[1 2 3 4 5 8]


In [81]:
# **Q16.4:** Stack arrays depth-wise using `np.dstack()`

depth_wise_stacked = np.dstack([arr1, arr2])
print(depth_wise_stacked)

[[[1 4]
  [2 5]
  [3 8]]]


In [82]:
# **Q16.5:** Create a column stack using `np.column_stack()`

column_stacked = np.column_stack([arr1, arr2])
print(column_stacked)

[[1 4]
 [2 5]
 [3 8]]


#### Question 17: Array Splitting Operations

In [83]:
import numpy as np

In [84]:
# **Q17.1:** Split an array into 3 equal parts using `np.split()`

array_ = np.array([1,3,5,2,4,6,8,9,19])
spliting = np.split(array_, 3)
for i, part in enumerate(spliting):
    print(f'Part {i+1}: {part}')

Part 1: [1 3 5]
Part 2: [2 4 6]
Part 3: [ 8  9 19]


In [85]:
# **Q17.2:** Split an array at specific indices using `np.split()`

spliting = np.split(array_, [3,6])
for i, part in enumerate(spliting):
    print(f"{i+1} : {part}")

1 : [1 3 5]
2 : [2 4 6]
3 : [ 8  9 19]


In [86]:
# **Q17.3:** Split an array horizontally using `np.hsplit()`

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
spliting = np.hsplit(arr_2d, 3)
for i, part in enumerate(spliting):
    print(f"Horigental part {i+1}:\n {part}")

Horigental part 1:
 [[1]
 [4]]
Horigental part 2:
 [[2]
 [5]]
Horigental part 3:
 [[3]
 [6]]


In [87]:
# **Q17.4:** Split an array vertically using `np.vsplit()`

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
spliting = np.vsplit(arr_2d, 2)
for i, part in enumerate(spliting):
    print(f"Vertical part {i+1}:\n {part}")

Vertical part 1:
 [[1 2 3]]
Vertical part 2:
 [[4 5 6]]


In [88]:
# **Q17.5:** Split an array into equal chunks using `np.array_split()`

chunks = np.array_split(array_, 4)
for i, chunk in enumerate(chunks):
    print(f"Chunck {i+1}: {chunk}")

Chunck 1: [1 3 5]
Chunck 2: [2 4]
Chunck 3: [6 8]
Chunck 4: [ 9 19]


#### Question 18: Array Repetition and Tiling

In [89]:
# **Q18.1:** Repeat each element of an array 3 times using `np.repeat()`

repeating = np.repeat(arr1, 3)
print(repeating)

[1 1 1 2 2 2 3 3 3]


In [90]:
# **Q18.2:** Repeat an entire array 2 times using `np.tile()`

tailed_array = np.tile(arr1, 2)
print(tailed_array)

[1 2 3 1 2 3]


In [91]:
# **Q18.3:** Repeat a 2D array using `np.tile()`

tailed_2d_array = np.tile(arr_2d, 2)
print(tailed_2d_array)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [95]:
# **Q18.4:** Create a pattern using `np.tile()`

pattern = np.tile(arr_2d, (2,3))
print(pattern)

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [100]:
# **Q18.5:** Repeat elements with different counts using `np.repeat()`

arr_ = [3,2,4]
repeating = np.repeat(arr1, arr_)
print(f"Original: {arr1}")
print(f"This many times repeating the original array at specific index:\n {arr_}")
print(f"Result : {repeating}")

Original: [1 2 3]
This many times repeating the original array at specific index:
 [3, 2, 4]
Result : [1 1 1 2 2 3 3 3 3]


#### Question 19: Array Comparison and Logical Operations

In [103]:
# **Q19.1:** Compare two arrays for equality using `np.array_equal()`

arr_a = [1, 2, 3]
arr_b = [1, 2, 3]
arr_c = [1, 4, 3]
print(np.array_equal(arr_a, arr_b))
print(np.array_equal(arr_a, arr_c))

True
False


In [117]:
# **Q19.2:** Check if arrays are close using `np.allclose()`

arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(np.allclose(arr_d, arr_e, atol=0.01))

True


In [133]:
# **Q19.3:** Apply logical AND operation between arrays

print(arr1)
print(np.logical_and(arr1 > 1, arr1 < 3))

[1 2 3]
[False  True False]


In [132]:
# **Q19.4:** Apply logical OR operation between arrays

print(arr1)
print(np.logical_or(arr1 == 1, arr1 == 3))

[1 2 3]
[ True False  True]


In [131]:
# **Q19.5:** Apply logical NOT operation to an array

print(arr1)
print(np.logical_not(arr1 == 1))

[1 2 3]
[False  True  True]


In [ ]:
#### Question 20: Array Set Operations

In [130]:
# **Q20.1:** Find unique elements in an array using `np.unique()`

arr = np.array([1,2,3,2,3,1,4,4,5,4,6,7,4,6,6,8])
print(f"Unique : {np.unique(arr)}")

Unique : [1 2 3 4 5 6 7 8]


In [129]:
# **Q20.2:** Find the intersection of two arrays using `np.intersect1d()`

arr_f = np.array([1, 2, 3, 4])
arr_g = np.array([3, 4, 5, 6])
print(f"Intersection : {np.intersect1d(arr_f, arr_g)}")

Intersection : [3 4]


In [128]:
# **Q20.3:** Find the union of two arrays using `np.union1d()`

print(f"Union : {np.union1d(arr_f, arr_g)}")

Union : [1 2 3 4 5 6]


In [142]:
# **Q20.4:** Find elements in first array but not in second using `np.setdiff1d()`

print(f"1st: {arr1}")
print(f"2nd: {arr_c}")
print(f"The elements in first array but not in second: \n{np.setdiff1d(arr1, arr_c)}")

1st: [1 2 3]
2nd: [1, 4, 3]
The elements in first array but not in second: 
[2]


In [141]:
# **Q20.5:** Find the symmetric difference between two arrays using `np.setxor1d()`

print(f"1st: {arr1}")
print(f"2nd: {arr_c}")
print(f"The symmetric difference between two arrays: \n {np.setxor1d(arr1, arr_c)}")

1st: [1 2 3]
2nd: [1, 4, 3]
The symmetric difference between two arrays: 
 [2 4]
